name: Cross Build
on: 
    push: 
        branches: 
            - develop

jobs: 
    Build: 
        name: Cross Build
        runs-on: ubuntu-latest

        steps: 
            - name: Check out
              uses: actions/checkout@v3

            - name: apt get
              run: |
                sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

            - name: Build
              run: |
                cd trunk
                sudo ./configure --cross-build --cc=aarch64-linux-gnu-gcc --cxx=aarch64-linux-gnu-g++ --ar=aarch64-linux-gnu-ar --ld=aarch64-linux-gnu-ld --randlib=aarch64-linux-gnu-randlib
                ls

            #- name: Upload build artifacts
              #uses: actions/upload-artifact@v3
              #with: 
                #path: |
                  #trunk/conf
                  #trunk/etc
                  #trunk/objs
                  #trunk/usr
